# =====================================================================================
# Achievements Config (v1) — Aug 17, 2025
# Совместимо с гибкими загрузчиками: простой YAML без экзотики.
# Конвенции:
#   • id — уникальный slug (^[a-z0-9_]+$)
#   • title/desc — локализация ru/en (en — опционально)
#   • category — одна из: onboarding, community, tools, market, quiz, mining, streak, meta
#   • rarity — common | rare | epic | legendary
#   • points — базовые баллы за выдачу достижения (XP)
#   • repeatable — можно ли получать снова (обычно false)
#   • condition:
#       type — counter | event | streak | value_reach | tiered
#       event — имя события из кода (эмитится сервисами/хендлерами)
#       counter_key — имя счётчика (в Redis или в UserService)
#       threshold — целевое значение
#       window_days — (опц.) окно для streak/сезонных активностей
#       tiers — (для tiered) массив порогов
#   • reward — побочные награды (бейдж, роль и т.п.) — опционально
#   • notify.template_ru — текст, который можно показать пользователю
# =====================================================================================

version: 1
updated_at: "2025-08-17"

defaults:
  rarity_points:
    common: 10
    rare: 25
    epic: 75
    legendary: 150
  icons:
    onboarding: "🧭"
    community: "💬"
    tools: "🧰"
    market: "📈"
    quiz: "🧠"
    mining: "⛏️"
    streak: "🔥"
    meta: "🏆"

# ---------------------------------------------------------------------
# Список ачивок
# ---------------------------------------------------------------------
achievements:

  # ============ ONBOARDING ============
  - id: onboarding_start
    category: onboarding
    rarity: common
    icon: "🧭"
    title:
      ru: "Добро пожаловать!"
      en: "Welcome Aboard!"
    desc:
      ru: "Впервые запустил(а) бота."
      en: "Used /start for the first time."
    points: 10
    repeatable: false
    condition:
      type: event
      event: user.start
    notify:
      template_ru: "🎉 Первое знакомство — достижение «Добро пожаловать!» (+10 XP)"

  - id: onboarding_menu
    category: onboarding
    rarity: common
    icon: "🧭"
    title:
      ru: "Исследователь меню"
    desc:
      ru: "Открыл(а) главное меню впервые."
    points: 10
    repeatable: false
    condition:
      type: event
      event: user.menu_opened
    notify:
      template_ru: "🧭 Меню покорено! (+10 XP)"

  - id: onboarding_bind_wallet
    category: onboarding
    rarity: rare
    icon: "🔗"
    title:
      ru: "Кошелёк на связи"
    desc:
      ru: "Привязал(а) криптокошелёк в боте."
    points: 25
    repeatable: false
    condition:
      type: event
      event: wallet.bound
    notify:
      template_ru: "🔗 Кошелёк привязан — надёжный старт! (+25 XP)"

  # ============ COMMUNITY ============
  - id: community_first_message
    category: community
    rarity: common
    icon: "💬"
    title:
      ru: "Первое слово"
    desc:
      ru: "Отправил(а) первое сообщение в чате."
    points: 10
    repeatable: false
    condition:
      type: event
      event: chat.first_message
    notify:
      template_ru: "💬 Начало положено! (+10 XP)"

  - id: community_talker_10
    category: community
    rarity: common
    icon: "💬"
    title:
      ru: "Разговорчивый"
    desc:
      ru: "Отправил(а) 10 сообщений."
    points: 15
    repeatable: false
    condition:
      type: counter
      event: chat.message  # инкрементируйте по каждому сообщению
      counter_key: user:msg_count
      threshold: 10
    notify:
      template_ru: "💬 10 сообщений — держим темп! (+15 XP)"

  - id: community_talker_100
    category: community
    rarity: rare
    icon: "💬"
    title:
      ru: "Голос чата"
    desc:
      ru: "Отправил(а) 100 сообщений."
    points: 40
    repeatable: false
    condition:
      type: counter
      event: chat.message
      counter_key: user:msg_count
      threshold: 100
    notify:
      template_ru: "🎙 100 сообщений — респект! (+40 XP)"

  - id: community_helpful_replies_5
    category: community
    rarity: rare
    icon: "🤝"
    title:
      ru: "Помощник"
    desc:
      ru: "Сделал(а) 5 ответов в ветках/реплаях."
    points: 30
    repeatable: false
    condition:
      type: counter
      event: chat.reply
      counter_key: user:reply_count
      threshold: 5
    notify:
      template_ru: "🤝 5 полезных ответов — красавчик! (+30 XP)"

  - id: community_inviter_1
    category: community
    rarity: rare
    icon: "🫂"
    title:
      ru: "Позвал друга"
    desc:
      ru: "Пригласил(а) 1 нового пользователя по реферальной ссылке."
    points: 35
    repeatable: false
    condition:
      type: counter
      event: referrals.joined
      counter_key: user:referrals
      threshold: 1
    notify:
      template_ru: "🫂 Первый реферал! (+35 XP)"

  - id: community_inviter_5
    category: community
    rarity: epic
    icon: "🫂"
    title:
      ru: "Амбассадор"
    desc:
      ru: "Пригласил(а) 5 пользователей."
    points: 90
    repeatable: false
    condition:
      type: counter
      event: referrals.joined
      counter_key: user:referrals
      threshold: 5
    notify:
      template_ru: "🫂🫂🫂 Амбассадор! (+90 XP)"

  # ============ TOOLS ============
  - id: tools_convert_first
    category: tools
    rarity: common
    icon: "🧰"
    title:
      ru: "Конвертер запущен"
    desc:
      ru: "Впервые воспользовался(лась) конвертацией."
    points: 10
    repeatable: false
    condition:
      type: event
      event: tool.convert.used
    notify:
      template_ru: "🔢 Первый расчёт конвертации! (+10 XP)"

  - id: tools_pnl_first
    category: tools
    rarity: common
    icon: "🧮"
    title:
      ru: "PNL впервые"
    desc:
      ru: "Посчитал(а) PnL."
    points: 10
    repeatable: false
    condition:
      type: event
      event: tool.pnl.used
    notify:
      template_ru: "🧮 PnL посчитан! (+10 XP)"

  - id: tools_roi_first
    category: tools
    rarity: common
    icon: "📊"
    title:
      ru: "ROI впервые"
    desc:
      ru: "Посчитал(а) ROI."
    points: 10
    repeatable: false
    condition:
      type: event
      event: tool.roi.used
    notify:
      template_ru: "📊 ROI посчитан! (+10 XP)"

  # ============ MARKET ============
  - id: market_price_btc_first
    category: market
    rarity: common
    icon: "📈"
    title:
      ru: "BTC-тикер"
    desc:
      ru: "Запросил(а) цену BTC впервые."
    points: 10
    repeatable: false
    condition:
      type: event
      event: market.price.btc
    notify:
      template_ru: "₿ Первый запрос цены BTC! (+10 XP)"

  - id: market_news_reader_5
    category: market
    rarity: rare
    icon: "📰"
    title:
      ru: "В теме"
    desc:
      ru: "Прочитал(а) 5 новостей через бота."
    points: 30
    repeatable: false
    condition:
      type: counter
      event: market.news.read
      counter_key: user:news_read
      threshold: 5
    notify:
      template_ru: "📰 Держишь руку на пульсе! (+30 XP)"

  # ============ QUIZ ============
  - id: quiz_first_correct
    category: quiz
    rarity: common
    icon: "🧠"
    title:
      ru: "Первый правильный"
    desc:
      ru: "Ответил(а) правильно в квизе."
    points: 15
    repeatable: false
    condition:
      type: event
      event: quiz.answer.correct
    notify:
      template_ru: "🧠 Есть контакт! (+15 XP)"

  - id: quiz_streak_3
    category: quiz
    rarity: rare
    icon: "🔥"
    title:
      ru: "Серия 3"
    desc:
      ru: "3 правильных подряд."
    points: 35
    repeatable: false
    condition:
      type: streak
      event: quiz.answer.correct
      threshold: 3
      window_days: 7
    notify:
      template_ru: "🔥 Серия из 3 правильных — красиво! (+35 XP)"

  - id: quiz_master_20
    category: quiz
    rarity: epic
    icon: "🏅"
    title:
      ru: "Квиз-мастер"
    desc:
      ru: "20 правильных ответов всего."
    points: 100
    repeatable: false
    condition:
      type: counter
      event: quiz.answer.correct
      counter_key: user:quiz_correct_total
      threshold: 20
    notify:
      template_ru: "🏅 Квиз-мастер! (+100 XP)"

  # ============ MINING GAME ============
  - id: mining_started
    category: mining
    rarity: common
    icon: "⛏️"
    title:
      ru: "Шахтёр-новичок"
    desc:
      ru: "Запустил(а) майнинг-игру."
    points: 15
    repeatable: false
    condition:
      type: event
      event: mining.game.started
    notify:
      template_ru: "⛏️ Добро пожаловать в шахту! (+15 XP)"

  - id: mining_first_rig
    category: mining
    rarity: rare
    icon: "🖥️"
    title:
      ru: "Первая ферма"
    desc:
      ru: "Купил(а) первый риг."
    points: 40
    repeatable: false
    condition:
      type: event
      event: mining.rig.bought_first
    notify:
      template_ru: "🖥️ Первая ферма — начало империи! (+40 XP)"

  - id: mining_hashrate_1_ths
    category: mining
    rarity: rare
    icon: "⚡"
    title:
      ru: "1 TH/s"
    desc:
      ru: "Достиг 1 TH/s совокупного хешрейта."
    points: 45
    repeatable: false
    condition:
      type: value_reach
      event: mining.hashrate.total
      threshold: 1.0
    notify:
      template_ru: "⚡ Хешрейт 1 TH/s! (+45 XP)"

  - id: mining_hashrate_10_ths
    category: mining
    rarity: epic
    icon: "⚡"
    title:
      ru: "10 TH/s"
    desc:
      ru: "Достиг 10 TH/s совокупного хешрейта."
    points: 110
    repeatable: false
    condition:
      type: value_reach
      event: mining.hashrate.total
      threshold: 10.0
    notify:
      template_ru: "⚡⚡⚡ 10 TH/s — мощно! (+110 XP)"

  - id: mining_revenue_0_01_btc
    category: mining
    rarity: epic
    icon: "💎"
    title:
      ru: "0.01 BTC добыто"
    desc:
      ru: "Суммарный доход в игре достиг 0.01 BTC (в эквиваленте)."
    points: 120
    repeatable: false
    condition:
      type: value_reach
      event: mining.revenue.total_btc_eq
      threshold: 0.01
    notify:
      template_ru: "💎 Грань пройдена — 0.01 BTC! (+120 XP)"

  - id: mining_tasks_10
    category: mining
    rarity: rare
    icon: "📋"
    title:
      ru: "Дисциплина — мать успеха"
    desc:
      ru: "Выполнил(а) 10 игровых заданий/квестов."
    points: 50
    repeatable: false
    condition:
      type: counter
      event: mining.tasks.completed
      counter_key: user:mining_tasks_done
      threshold: 10
    notify:
      template_ru: "📋 10 задач закрыто! (+50 XP)"

  # ============ STREAK / ACTIVITY ============
  - id: streak_daily_3
    category: streak
    rarity: common
    icon: "🔥"
    title:
      ru: "3-дневная серия"
    desc:
      ru: "Заходил(а) в бот 3 дня подряд."
    points: 20
    repeatable: false
    condition:
      type: streak
      event: user.daily_checkin
      threshold: 3
      window_days: 3
    notify:
      template_ru: "🔥 Держишь 3-дневную серию! (+20 XP)"

  - id: streak_daily_7
    category: streak
    rarity: rare
    icon: "🔥"
    title:
      ru: "7-дневная серия"
    desc:
      ru: "7 дней подряд активность в боте."
    points: 60
    repeatable: false
    condition:
      type: streak
      event: user.daily_checkin
      threshold: 7
      window_days: 7
    notify:
      template_ru: "🔥🔥 Неделя в строю! (+60 XP)"

  - id: streak_daily_30
    category: streak
    rarity: epic
    icon: "🔥"
    title:
      ru: "Железная дисциплина"
    desc:
      ru: "30 дней подряд активность в боте."
    points: 180
    repeatable: false
    condition:
      type: streak
      event: user.daily_checkin
      threshold: 30
      window_days: 30
    notify:
      template_ru: "🔥🔥🔥 Месяц без перерыва! (+180 XP)"

  # ============ META / TIERED EXAMPLE ============
  - id: meta_power_user
    category: meta
    rarity: legendary
    icon: "🏆"
    title:
      ru: "Power User"
    desc:
      ru: "Суммарный «уровень» активности: сообщения, квизы, инструменты."
    points: 150
    repeatable: false
    condition:
      type: tiered
      # В коде агрегируйте суммарный индекс активности в counter_key
      counter_key: user:power_index
      tiers:
        - threshold: 100   # начинаем считать Power User с 100 баллов активности
        - threshold: 300
        - threshold: 600
      # Рекомендуется выдавать финальную ступень (например, при 600)
    notify:
      template_ru: "🏆 Мощный пользователь! (+150 XP)"

# ---------------------------------------------------------------------
# Подсказки по событиям (для разработчика):
#   Эмитируйте события при нужных действиях:
#     user.start, user.menu_opened, wallet.bound
#     chat.message, chat.reply, chat.first_message
#     referrals.joined
#     tool.convert.used, tool.pnl.used, tool.roi.used
#     market.price.btc, market.news.read
#     quiz.answer.correct
#     mining.game.started, mining.rig.bought_first
#     mining.hashrate.total (value_reach), mining.revenue.total_btc_eq (value_reach)
#     mining.tasks.completed
#     user.daily_checkin
#
#   Для counter/streak/value_reach:
#     • counter_key — имя вашего счётчика (Redis/UserService)
#     • increment/maintain выполняется в сервисах/хендлерах;
#     • AchievementService только читает и принимает решение (или сам инкрементит,
#       если так реализовано в вашей версии — структура остаётся совместимой).
# ---------------------------------------------------------------------